package es.uma.proyecto.test;

import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.assertThat;

import java.io.IOException;
import java.io.InputStream;
import java.text.ParseException;
import java.util.HashMap;
import java.util.Map;
import java.util.Properties;

import org.junit.After;
import org.junit.Before;
import org.junit.BeforeClass;
// Generated by Selenium IDE
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Keys;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

import es.uma.informatica.sii.anotaciones.Requisitos;

public class ProyectoIT {
	private WebDriver driver;
	private Map<String, Object> vars;
	JavascriptExecutor js;

	private static String baseURL;
	private static Map<String,String> propiedadesExtra = new HashMap<>();

	@BeforeClass
	public static void setupClass() {
		String server="localhost";
		try (InputStream is = ProyectoIT.class.getClassLoader().getResourceAsStream("pom.properties")) {
			Properties pomProperties = new Properties();
			pomProperties.load(is);
			server=pomProperties.getProperty("server.host");
			String databaseURL = "jdbc:mysql://"+server+":3306/sii";
			propiedadesExtra.put("javax.persistence.jdbc.url", databaseURL);
		} catch (IOException e) {
			e.printStackTrace();
		}
		baseURL="http://"+server+":8080/proyecto-war/";
	}

	@Before
	public void setUp() throws ParseException {
		driver = new ChromeDriver();
		js = (JavascriptExecutor) driver;
		vars = new HashMap<String, Object>();
	}
	
	@After
	public void tearDown() {
		driver.quit();
	}
	
	@Requisitos({"RF1"})
	@Test
	/**
	 * Acceso a la aplicación por parte de un admnistrativo dado
	 * un usuario y su contraseña
	 */
	public void iniciarSesionAdmin() {
		driver.get("http://0.0.0.0:8080/proyecto-war/");
		driver.manage().window().setSize(new Dimension(670, 734));
		driver.findElement(By.id("login:user")).click();
		driver.findElement(By.id("login:user")).sendKeys("ponciano");
		driver.findElement(By.id("login:pass")).sendKeys("ponciano");
		driver.findElement(By.id("login:botonLogin")).click();
		assertThat(driver.findElement(By.cssSelector("h3 > span")).getText(), is("ADMINISTRADORES"));
	}
	

	@Test
	/**
	 * Error al intentar acceder a la aplicacion dejando los campos vacios,
	 * se le indica al cliente que debe rellenarlos
	 */
	public void inciarSesionCamposVacios() {
		driver.get("http://0.0.0.0:8080/proyecto-war/");
		driver.manage().window().setSize(new Dimension(790, 866));
		driver.findElement(By.id("login:botonLogin")).click();
		assertThat(driver.findElement(By.id("login:userMessage")).getText(), is("Valor obligatorio"));
		assertThat(driver.findElement(By.id("login:passwordMessage")).getText(), is("Valor obligatorio"));
	}
	
	@Requisitos({"RF10"})
	@Test
	/*
	 * Acceso a la aplicacion por parte de un cliente normal
	 * es decir, aquel que no es administrativo y tendrá asociada una cuenta bancaria
	 * Este accedera a index.xhtml y observara sus datos
	 * Podra ser Persona autorizada o un Individuo
	 */
	public void iniciarSesionNoAdmin() {
		driver.get("http://0.0.0.0:8080/proyecto-war/");
		driver.manage().window().setSize(new Dimension(790, 866));
		driver.findElement(By.id("login:user")).click();
		driver.findElement(By.id("login:user")).sendKeys("juan");
		driver.findElement(By.id("login:pass")).sendKeys("juan");
		driver.findElement(By.cssSelector("p")).click();
		driver.findElement(By.id("login:botonLogin")).click();
		driver.findElement(By.cssSelector("p:nth-child(1)")).click();
		assertThat(driver.findElement(By.cssSelector("p:nth-child(1)")).getText(), is("BUENAS TARDES INDIVIDUAL JUAN ¿QUÉ ACCIÓN REALIZARÁ?"));
	}
	
	
	@Requisitos({"RF10"})
	@Test
	/*
	 * Error al intentar acceder a la aplicacion con una mala contraseña
	 */
	public void iniciarSesionPasswordMal() {
		driver.get("http://0.0.0.0:8080/proyecto-war/");
		driver.manage().window().setSize(new Dimension(790, 866));
		driver.findElement(By.id("login:user")).click();
		driver.findElement(By.id("login:user")).sendKeys("ponciano");
		driver.findElement(By.id("login:pass")).sendKeys("asdsa");
		driver.findElement(By.id("login:botonLogin")).click();
		driver.findElement(By.cssSelector(".intro-contr")).click();
		assertThat(driver.findElement(By.id("login:passwordMessage")).getText(), is("La contraseña no coincide"));
	}
	
	@Requisitos({"RF10"})
	@Test
	/*
	 * Error al intentar acceder a la aplicacion con un usuario incorrecto
	 */
	public void iniciarSesionUsuarioNoExiste() {
		driver.get("http://0.0.0.0:8080/proyecto-war/");
		driver.manage().window().setSize(new Dimension(790, 866));
		driver.findElement(By.id("login:user")).click();
		driver.findElement(By.id("login:user")).sendKeys("adsfasf");
		driver.findElement(By.id("login:pass")).click();
		driver.findElement(By.id("login:pass")).sendKeys("fdasfa");
		driver.findElement(By.id("login:botonLogin")).click();
		driver.findElement(By.cssSelector(".intro-usu")).click();
		assertThat(driver.findElement(By.id("login:userMessage")).getText(), is("La cuenta no existe"));
	}
	

	@Test @SuppressWarnings("deprecation")
  	public void mostrarCuentaReferenciaTest() {
		driver.get("http://0.0.0.0:8080/proyecto-war/");
		driver.manage().window().setSize(new Dimension(929, 918));
		driver.findElement(By.id("login:user")).click();
		driver.findElement(By.id("login:user")).sendKeys("ponciano");
		driver.findElement(By.id("login:pass")).sendKeys("ponciano");
		driver.findElement(By.id("login:botonLogin")).click();
		driver.findElement(By.cssSelector("div:nth-child(5) > button:nth-child(3)")).click();
		driver.findElement(By.id("mostrarCuentasRef:iban")).click();
		driver.findElement(By.id("mostrarCuentasRef:iban")).sendKeys("VG57DDVS5173214964983931");
		driver.findElement(By.id("mostrarCuentasRef:mostrarCuentas")).click();
		assertThat(driver.findElement(By.cssSelector("p:nth-child(4) > i")).getText(), is("BANCOS PABLO SA"));
		assertThat(driver.findElement(By.cssSelector("p:nth-child(10) > i")).getText(), is("DOLAR"));
		assertThat(driver.findElement(By.cssSelector("p:nth-child(2) > i")).getText(), is("VG57DDVS5173214964983931"));
  	}

	@Test @SuppressWarnings("deprecation")
	public void mostrarCuentaSegregadaTest() {
		driver.get("http://0.0.0.0:8080/proyecto-war/");
		driver.manage().window().setSize(new Dimension(929, 918));
		driver.findElement(By.id("login:user")).click();
		driver.findElement(By.id("login:user")).sendKeys("ponciano");
		driver.findElement(By.id("login:pass")).sendKeys("ponciano");
		driver.findElement(By.id("login:botonLogin")).click();
		driver.findElement(By.cssSelector("div:nth-child(5) > button:nth-child(2)")).click();
		driver.findElement(By.id("mostrarCuentas:iban")).click();
		driver.findElement(By.id("mostrarCuentas:iban")).sendKeys("FR5514508000502273293129K55");
		driver.findElement(By.id("mostrarCuentas:mostrarCuentas")).click();
		assertThat(driver.findElement(By.cssSelector("p:nth-child(7) > i")).getText(), is("SEGREGADA"));
		assertThat(driver.findElement(By.cssSelector("p:nth-child(9) > i")).getText(), is("HN47QUXH11325678769785549996"));
		assertThat(driver.findElement(By.cssSelector("p:nth-child(6) > i")).getText(), is("NO TIENE"));
		assertThat(driver.findElement(By.cssSelector("p:nth-child(4) > i")).getText(), is("ACTIVE"));
	}

	@Test @SuppressWarnings("deprecation")
	public void mostrarCuentaPooledTest() {
		driver.get("http://0.0.0.0:8080/proyecto-war/");
		driver.manage().window().setSize(new Dimension(929, 918));
		driver.findElement(By.id("login:user")).click();
		driver.findElement(By.id("login:user")).sendKeys("ponciano");
		driver.findElement(By.id("login:pass")).sendKeys("ponciano");
		driver.findElement(By.id("login:botonLogin")).click();
		driver.findElement(By.cssSelector("div:nth-child(5) > button:nth-child(2)")).click();
		driver.findElement(By.id("mostrarCuentas:iban")).click();
		driver.findElement(By.id("mostrarCuentas:iban")).sendKeys("ES8400817251647192321264");
		driver.findElement(By.id("mostrarCuentas:mostrarCuentas")).click();
		assertThat(driver.findElement(By.cssSelector("p:nth-child(2) > i")).getText(), is("ES8400817251647192321264"));
		assertThat(driver.findElement(By.cssSelector("p:nth-child(7) > i")).getText(), is("POOLED"));
		assertThat(driver.findElement(By.cssSelector("p:nth-child(6) > i")).getText(), is("NO TIENE"));
	}
	
	  @Test
  public void crearEmpresa() {
    driver.get("http://0.0.0.0:8080/proyecto-war/");
    driver.manage().window().setSize(new Dimension(945, 1028));
    driver.findElement(By.id("login:user")).click();
    driver.findElement(By.id("login:user")).sendKeys("ponciano");
    driver.findElement(By.id("login:pass")).sendKeys("ponciano");
    driver.findElement(By.id("login:botonLogin")).click();
    driver.findElement(By.cssSelector("div:nth-child(4) > button:nth-child(7)")).click();
    driver.findElement(By.id("crearEmp:identCrearEmp")).click();
    driver.findElement(By.id("crearEmp:identCrearEmp")).sendKeys("7654321");
    driver.findElement(By.id("crearEmp:nombreCrearEmp")).click();
    driver.findElement(By.id("crearEmp:nombreCrearEmp")).sendKeys("1");
    driver.findElement(By.id("crearEmp:direcCrearEmp")).click();
    driver.findElement(By.id("crearEmp:direcCrearEmp")).sendKeys("1");
    driver.findElement(By.id("crearEmp:ciudadCrearEmp")).click();
    driver.findElement(By.id("crearEmp:ciudadCrearEmp")).sendKeys("1");
    driver.findElement(By.id("crearEmp:codPostCrearEmp")).click();
    driver.findElement(By.id("crearEmp:codPostCrearEmp")).sendKeys("1");
    driver.findElement(By.id("crearEmp:PaisCrearEmp")).click();
    driver.findElement(By.id("crearEmp:PaisCrearEmp")).sendKeys("1");
    driver.findElement(By.id("crearEmp:BajaCrearEmp")).click();
    driver.findElement(By.id("crearEmp:crearEmpresa")).click();
    driver.findElement(By.cssSelector(".content > div:nth-child(4) > button:nth-child(2)")).click();
    driver.findElement(By.id("mostrarCl:mostrarCliente")).click();
    assertThat(driver.findElement(By.cssSelector("#DatosEmpresa > p:nth-child(3) > i")).getText(), is("7654321"));
  }
  @Test
  public void crearIndividual() {
    driver.get("http://0.0.0.0:8080/proyecto-war/");
    driver.manage().window().setSize(new Dimension(945, 1028));
    driver.findElement(By.id("login:user")).click();
    driver.findElement(By.id("login:user")).sendKeys("ponciano");
    driver.findElement(By.id("login:pass")).sendKeys("ponciano");
    driver.findElement(By.id("login:botonLogin")).click();
    driver.findElement(By.cssSelector("div:nth-child(4) > button:nth-child(6)")).click();
    driver.findElement(By.id("fCrear:identCrearInd")).click();
    driver.findElement(By.id("fCrear:identCrearInd")).sendKeys("1234567");
    driver.findElement(By.id("fCrear:identUsuCrearInd")).click();
    driver.findElement(By.id("fCrear:identUsuCrearInd")).sendKeys("1234567");
    driver.findElement(By.id("fCrear:nombreCrearInd")).click();
    driver.findElement(By.id("fCrear:nombreCrearInd")).sendKeys("1");
    driver.findElement(By.id("fCrear:apellidosCrearInd")).click();
    driver.findElement(By.id("fCrear:apellidosCrearInd")).sendKeys("1");
    driver.findElement(By.id("fCrear:fechaNacCrearInd")).click();
    driver.findElement(By.id("fCrear:fechaNacCrearInd")).sendKeys("1");
    driver.findElement(By.id("fCrear:direcCrearInd")).click();
    driver.findElement(By.id("fCrear:ciudadCrearInd")).click();
    driver.findElement(By.id("fCrear:ciudadCrearInd")).sendKeys("1");
    driver.findElement(By.id("fCrear:direcCrearInd")).click();
    driver.findElement(By.id("fCrear:direcCrearInd")).sendKeys("1");
    driver.findElement(By.id("fCrear:codPostCrearInd")).click();
    driver.findElement(By.id("fCrear:codPostCrearInd")).sendKeys("1");
    driver.findElement(By.id("fCrear:PaisCrearInd")).click();
    driver.findElement(By.id("fCrear:PaisCrearInd")).sendKeys("1");
    driver.findElement(By.id("fCrear:BajaCrearInd")).click();
    driver.findElement(By.id("fCrear:crearCliente")).click();
    driver.findElement(By.cssSelector(".content > div:nth-child(4) > button:nth-child(2)")).click();
    driver.findElement(By.id("mostrarCl:mostrarCliente")).click();
    driver.findElement(By.cssSelector("#DatosInd > p:nth-child(3) > i")).click();
    assertThat(driver.findElement(By.cssSelector("#DatosInd > p:nth-child(3) > i")).getText(), is("1234567"));
  }

  	@Requisitos({"RF4"})
	@Test @SuppressWarnings("deprecation")
  	/*
  	 * Dar de baja cliente
  	 */
	public void bajaCliente() {
		driver.get("http://0.0.0.0:8080/proyecto-war/");
		driver.manage().window().setSize(new Dimension(929, 918));
		driver.findElement(By.id("login:user")).click();
		driver.findElement(By.id("login:user")).sendKeys("ponciano");
		driver.findElement(By.id("login:pass")).sendKeys("ponciano");
		driver.findElement(By.id("login:botonLogin")).click();
		driver.findElement(By.cssSelector(".content > div:nth-child(4) > button:nth-child(2)")).click();
		driver.findElement(By.id("mostrarCl:identMostrar")).click();
		driver.findElement(By.id("mostrarCl:identMostrar")).sendKeys("P3310693A");
		driver.findElement(By.id("mostrarCl:mostrarCliente")).click();
		assertThat(driver.findElement(By.cssSelector("p:nth-child(5) > i")).getText(), is("ALTA"));
		assertThat(driver.findElement(By.cssSelector("p:nth-child(7) > i")).getText(), is("NO TIENE"));
		driver.findElement(By.cssSelector("div:nth-child(5) > button:nth-child(5)")).click();
		driver.findElement(By.id("fBaja:identBaja")).click();
		driver.findElement(By.id("fBaja:identBaja")).sendKeys("P3310693A");
		driver.findElement(By.id("fBaja:darBaja")).click();
		driver.findElement(By.cssSelector(".content > div:nth-child(4) > button:nth-child(2)")).click();
		driver.findElement(By.id("mostrarCl:mostrarCliente")).click();
		assertThat(driver.findElement(By.cssSelector("p:nth-child(5) > i")).getText(), is("BAJA"));
	}

  	
  	@Requisitos({"RF6"})
	@Test 
  	/*
  	 * La aplicación permitirá a un administrativo añadir 
  	 * personas autorizadas a las cuentas que pertenezcan a 
  	 * cliente que son personas jurídicas. 
  	 */
	public void addPersonaAutorizadaEmpresa() {
		driver.get("http://0.0.0.0:8080/proyecto-war/");
		driver.manage().window().setSize(new Dimension(790, 866));
		driver.findElement(By.id("login:user")).click();
		driver.findElement(By.id("login:user")).sendKeys("ponciano");
		driver.findElement(By.id("login:pass")).sendKeys("ponciano");
		driver.findElement(By.cssSelector(".centrar-elem")).click();
		driver.findElement(By.id("login:botonLogin")).click();
		driver.findElement(By.cssSelector("div:nth-child(6) > button:nth-child(3)")).click();
		driver.findElement(By.id("fAPA:idEmpAPA")).click();
		driver.findElement(By.id("fAPA:idEmpAPA")).sendKeys("P3310693A");
		driver.findElement(By.id("fAPA:idPerAPA")).click();
		driver.findElement(By.id("fAPA:idPerAPA")).sendKeys("Victor");
		driver.findElement(By.id("fAPA:tipoAPA1")).sendKeys("Victor");
		driver.findElement(By.id("fAPA:tipoAPA2")).sendKeys("Baki");
		driver.findElement(By.id("fAPA:tipoAPA3")).sendKeys("Calle falsa");
		driver.findElement(By.id("fAPA:tipoAPA7")).click();
		driver.findElement(By.id("fAPA:tipoAPA")).click();
		driver.findElement(By.id("fAPA:tipoAPA")).sendKeys("Ninguna");
		driver.findElement(By.id("fAPA:addAutor")).click();
		driver.findElement(By.cssSelector("div:nth-child(6) > button:nth-child(2)")).click();
		driver.findElement(By.id("mostrarPersona:persMostrar")).click();
		driver.findElement(By.id("mostrarPersona:persMostrar")).sendKeys("victor");
		driver.findElement(By.id("mostrarPersona:mostrarCuentas")).click();
		assertThat(driver.findElement(By.cssSelector("#DatosPersona > p:nth-child(3) > i")).getText(), is("VICTOR"));
		driver.findElement(By.cssSelector("p:nth-child(11)")).click();
		assertThat(driver.findElement(By.cssSelector("p:nth-child(11) > i")).getText(), is("{PABLONOTOQUES S.A.(P3310693A)}"));
	}
  	
  	@Requisitos({"RF6"})
	@Test
	/**
	 * Test para la comprobación de que la persona 
	 * autorizada ya estaba como tal en la empresa
	 */
	public void addPersonaAutorizadaEmpresaYaExiste() {
		driver.get("http://0.0.0.0:8080/proyecto-war/");
		driver.manage().window().setSize(new Dimension(790, 866));
		driver.findElement(By.id("login:user")).click();
		driver.findElement(By.id("login:user")).sendKeys("ponciano");
		driver.findElement(By.id("login:pass")).sendKeys("ponciano");
		driver.findElement(By.id("login:botonLogin")).click();
		driver.findElement(By.cssSelector("div:nth-child(6) > button:nth-child(4)")).click();
		driver.findElement(By.id("cAPA:idEmpCPA")).click();
		driver.findElement(By.id("cAPA:idEmpCPA")).click();
		driver.findElement(By.id("cAPA:idEmpCPA")).sendKeys("P3310693A");
		driver.findElement(By.id("cAPA:idPerCPA")).click();
		driver.findElement(By.id("cAPA:idPerCPA")).click();
		driver.findElement(By.id("cAPA:idPerCPA")).sendKeys("PATest");
		driver.findElement(By.id("cAPA:tipoCPA")).sendKeys("Ninguna");
		driver.findElement(By.id("cAPA:addAutorC")).click();
		driver.findElement(By.cssSelector("div:nth-child(6) > button:nth-child(2)")).click();
		driver.findElement(By.cssSelector("#mostrarPersona > p")).click();
		driver.findElement(By.id("mostrarPersona:persMostrar")).click();
		driver.findElement(By.id("mostrarPersona:persMostrar")).sendKeys("PATest");
		driver.findElement(By.id("mostrarPersona:persMostrar")).sendKeys(Keys.ENTER);
		driver.findElement(By.cssSelector("#DatosPersona > p:nth-child(3)")).click();
		assertThat(driver.findElement(By.cssSelector("#DatosPersona > p:nth-child(3) > i")).getText(), is("PATEST"));
		driver.findElement(By.cssSelector("p:nth-child(11)")).click();
		assertThat(driver.findElement(By.cssSelector("p:nth-child(11) > i")).getText(), is("{PABLONOTOQUES S.A.(P3310693A)}"));
	}

  	@Requisitos({"RF3"})
	@Test
	/**
	 * Comprobacion de la correcta modificación de un cliente ya creado,
	 * se introduce desde una cuenta admin los datos del cliente para modificar
	 * y luego se comprueba que, en efecto, se han modificado
	 */
  	public void modificarClienteTest() {
		driver.get("http://0.0.0.0:8080/proyecto-war/");
		driver.manage().window().setSize(new Dimension(929, 918));
		driver.findElement(By.id("login:user")).click();
		driver.findElement(By.id("login:user")).sendKeys("ponciano");
		driver.findElement(By.id("login:pass")).sendKeys("ponciano");
		driver.findElement(By.id("login:botonLogin")).click();
		driver.findElement(By.cssSelector(".content > div:nth-child(4) > button:nth-child(2)")).click();
		driver.findElement(By.id("mostrarCl:identMostrar")).click();
		driver.findElement(By.id("mostrarCl:identMostrar")).sendKeys("P3310693A");
		driver.findElement(By.id("mostrarCl:mostrarCliente")).click();
		assertThat(driver.findElement(By.cssSelector("p:nth-child(9) > i")).getText(), is("SERBIA"));
		assertThat(driver.findElement(By.cssSelector("p:nth-child(10) > i")).getText(), is("NOTIENE"));
		assertThat(driver.findElement(By.cssSelector("p:nth-child(11) > i")).getText(), is("PAISES BAJOS"));
		driver.findElement(By.cssSelector("div:nth-child(5) > button:nth-child(2)")).click();
		driver.findElement(By.cssSelector("#mostrarCl button")).click();
		driver.findElement(By.cssSelector("div:nth-child(4) > button:nth-child(4)")).click();
		driver.findElement(By.id("fMod:pais1Mod")).click();
		driver.findElement(By.id("fMod:pais1Mod")).sendKeys("FRANCIA");
		driver.findElement(By.id("fMod:ciudad1Mod")).click();
		driver.findElement(By.id("fMod:ciudad1Mod")).sendKeys("CUENCA");
		driver.findElement(By.id("fMod:dir1Mod")).click();
		driver.findElement(By.id("fMod:cp1Mod")).click();
		driver.findElement(By.id("fMod:cp1Mod")).sendKeys("29003");
		driver.findElement(By.id("fMod:modificar")).click();
		driver.findElement(By.cssSelector(".content > div:nth-child(4) > button:nth-child(2)")).click();
		driver.findElement(By.id("mostrarCl:mostrarCliente")).click();
		assertThat(driver.findElement(By.cssSelector("p:nth-child(11) > i")).getText(), is("FRANCIA"));
		assertThat(driver.findElement(By.cssSelector("p:nth-child(10) > i")).getText(), is("29003"));
		assertThat(driver.findElement(By.cssSelector("p:nth-child(9) > i")).getText(), is("CUENCA"));

		
  }
  	@Requisitos({"RF2"})
	@Test 
  	/*
  	 * Dar de alta cliente
  	 */
  public void altaCliente() {
    driver.get("http://0.0.0.0:8080/proyecto-war/");
    driver.manage().window().setSize(new Dimension(790, 866));
    driver.findElement(By.id("login:user")).click();
    driver.findElement(By.id("login:user")).sendKeys("ponciano");
    driver.findElement(By.id("login:pass")).sendKeys("ponciano");
    driver.findElement(By.id("login:botonLogin")).click();
    driver.findElement(By.cssSelector("div:nth-child(4) > button:nth-child(5)")).click();
    driver.findElement(By.id("fBaja:identBaja")).click();
    driver.findElement(By.id("fBaja:identBaja")).click();
    driver.findElement(By.id("fBaja:identBaja")).sendKeys("63937528N");
    driver.findElement(By.id("fBaja:darBaja")).click();
    driver.findElement(By.cssSelector(".content > div:nth-child(4) > button:nth-child(2)")).click();
    driver.findElement(By.id("mostrarCl:mostrarCliente")).click();
    assertThat(driver.findElement(By.cssSelector("p:nth-child(5) > i")).getText(), is("BAJA"));
    driver.findElement(By.cssSelector("div:nth-child(5) > button:nth-child(3)")).click();
    driver.findElement(By.cssSelector("div:nth-child(5) > button:nth-child(6)")).click();
    driver.findElement(By.cssSelector("div:nth-child(5) > button:nth-child(3)")).click();
    driver.findElement(By.id("fAlta:darAlta")).click();
    driver.findElement(By.cssSelector(".content > div:nth-child(4) > button:nth-child(2)")).click();
    driver.findElement(By.id("mostrarCl:mostrarCliente")).click();
    assertThat(driver.findElement(By.cssSelector("p:nth-child(5) > i")).getText(), is("ALTA"));
  }
  	
  	@Requisitos({"RF9"})
	@Test 
  	/*
  	 * MeLa aplicación permitirá a un administrativo cerrar una cuenta bancaria. 
  	 * Solo se puede cerrar una cuenta que tenga saldo 0 (en todas sus divisas). 
  	 * Una cuenta cerrada no se elimina, por si es necesario reportarla en algún informe.
  	 */
  public void cierreCuenta() {
    driver.get("http://0.0.0.0:8080/proyecto-war/");
    driver.manage().window().setSize(new Dimension(790, 866));
    driver.findElement(By.id("login:user")).click();
    driver.findElement(By.id("login:user")).sendKeys("ponciano");
    driver.findElement(By.id("login:pass")).sendKeys("ponciano");
    driver.findElement(By.id("login:botonLogin")).click();
    driver.findElement(By.cssSelector("div:nth-child(5) > button:nth-child(6)")).click();
    driver.findElement(By.id("fCer:ibanCer")).click();
    driver.findElement(By.id("fCer:ibanCer")).sendKeys("NL63ABNA6548268733");
    driver.findElement(By.id("fCer:cerra")).click();
    driver.findElement(By.cssSelector("div:nth-child(5) > button:nth-child(2)")).click();
    driver.findElement(By.id("mostrarCuentas:mostrarCuentas")).click();
    assertThat(driver.findElement(By.cssSelector("p:nth-child(4) > i")).getText(), is("ACTIVE"));
    driver.findElement(By.cssSelector("div:nth-child(6) > button:nth-child(3)")).click();
    driver.findElement(By.cssSelector("#mostrarCuentasRef tr:nth-child(1)")).click();
    driver.findElement(By.id("mostrarCuentasRef:iban")).sendKeys("VG57DDVS5173214964983931");
    driver.findElement(By.id("mostrarCuentasRef:mostrarCuentas")).click();
    assertThat(driver.findElement(By.cssSelector("p:nth-child(7) > i")).getText(), is("100.0"));
  }
}